2025-09-20 12:17:03.306 [main] ERROR TestFailureLogger - ❌ TEST FAILED: testcases.TC02_HomePage.validateCreateAdmin_P (Duration: 5245 ms)
2025-09-20 12:17:03.439 [main] ERROR TestFailureLogger - Failure reason: expected [true] but found [false]
2025-09-20 12:17:03.440 [main] ERROR TestFailureLogger - Stack trace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.failNotEquals(Assert.java:1578) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.assertTrue(Assert.java:57) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.assertTrue(Assert.java:67) ~[testng-7.8.0.jar:7.8.0]
	at testcases.TC02_HomePage.validateCreateAdmin_P(TC02_HomePage.java:46) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.8.0.jar:7.8.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:848) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestRunner.run(TestRunner.java:621) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:336) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1275) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuites(TestNG.java:1114) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.run(TestNG.java:1082) [testng-7.8.0.jar:7.8.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105) [testng-rt.jar:?]
2025-09-20 12:17:03.462 [main] ERROR TestFailureLogger - Test context information:
2025-09-20 12:17:03.462 [main] ERROR TestFailureLogger -   - Test name: Create PIM and Admin !
2025-09-20 12:17:03.462 [main] ERROR TestFailureLogger -   - Output directory: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-output\Running positive scenarios on main list of home page
2025-09-20 12:17:03.524 [main] ERROR TestFailureLogger -   - Start date: 2025-09-20T12:16:26.298+0300
2025-09-20 12:17:03.524 [main] ERROR TestFailureLogger -   - End date: null
2025-09-20 12:17:03.524 [main] ERROR TestFailureLogger -   - Failed tests count: 0
2025-09-20 12:17:03.524 [main] ERROR TestFailureLogger -   - Passed tests count: 1
2025-09-20 12:17:03.525 [main] ERROR TestFailureLogger -   - Skipped tests count: 0
2025-09-20 12:17:03.944 [main] ERROR TestFailureLogger - Failure report generated: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-reports\testcases.TC02_HomePage_validateCreateAdmin_P_2025-09-20_12-17-03_failure_report.html
2025-09-20 12:21:13.110 [main] ERROR TestFailureLogger - ❌ TEST FAILED: testcases.TC02_HomePage.validateCreateAdmin_P (Duration: 5870 ms)
2025-09-20 12:21:13.121 [main] ERROR TestFailureLogger - Failure reason: expected [true] but found [false]
2025-09-20 12:21:13.121 [main] ERROR TestFailureLogger - Stack trace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.failNotEquals(Assert.java:1578) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.assertTrue(Assert.java:57) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.assertTrue(Assert.java:67) ~[testng-7.8.0.jar:7.8.0]
	at testcases.TC02_HomePage.validateCreateAdmin_P(TC02_HomePage.java:46) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.8.0.jar:7.8.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:848) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestRunner.run(TestRunner.java:621) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:336) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1275) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuites(TestNG.java:1114) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.run(TestNG.java:1082) [testng-7.8.0.jar:7.8.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105) [testng-rt.jar:?]
2025-09-20 12:21:13.171 [main] ERROR TestFailureLogger - Test context information:
2025-09-20 12:21:13.172 [main] ERROR TestFailureLogger -   - Test name: Create PIM and Admin !
2025-09-20 12:21:13.172 [main] ERROR TestFailureLogger -   - Output directory: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-output\Running positive scenarios on main list of home page
2025-09-20 12:21:13.200 [main] ERROR TestFailureLogger -   - Start date: 2025-09-20T12:20:39.697+0300
2025-09-20 12:21:13.200 [main] ERROR TestFailureLogger -   - End date: null
2025-09-20 12:21:13.201 [main] ERROR TestFailureLogger -   - Failed tests count: 0
2025-09-20 12:21:13.202 [main] ERROR TestFailureLogger -   - Passed tests count: 1
2025-09-20 12:21:13.202 [main] ERROR TestFailureLogger -   - Skipped tests count: 0
2025-09-20 12:21:13.559 [main] ERROR TestFailureLogger - Failure report generated: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-reports\testcases.TC02_HomePage_validateCreateAdmin_P_2025-09-20_12-21-13_failure_report.html
2025-09-20 12:32:13.313 [main] ERROR TestFailureLogger - ❌ TEST FAILED: testcases.TC02_HomePage.validateCreateAdmin_P (Duration: 6487 ms)
2025-09-20 12:32:13.480 [main] ERROR TestFailureLogger - Failure reason: expected [true] but found [false]
2025-09-20 12:32:13.480 [main] ERROR TestFailureLogger - Stack trace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.failNotEquals(Assert.java:1578) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.assertTrue(Assert.java:57) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.assertTrue(Assert.java:67) ~[testng-7.8.0.jar:7.8.0]
	at testcases.TC02_HomePage.validateCreateAdmin_P(TC02_HomePage.java:46) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.8.0.jar:7.8.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:848) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestRunner.run(TestRunner.java:621) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:336) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1275) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuites(TestNG.java:1114) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.run(TestNG.java:1082) [testng-7.8.0.jar:7.8.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105) [testng-rt.jar:?]
2025-09-20 12:32:13.759 [main] ERROR TestFailureLogger - Test context information:
2025-09-20 12:32:13.759 [main] ERROR TestFailureLogger -   - Test name: Create PIM and Admin !
2025-09-20 12:32:13.759 [main] ERROR TestFailureLogger -   - Output directory: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-output\Running positive scenarios on main list of home page
2025-09-20 12:32:13.807 [main] ERROR TestFailureLogger -   - Start date: 2025-09-20T12:31:34.288+0300
2025-09-20 12:32:13.807 [main] ERROR TestFailureLogger -   - End date: null
2025-09-20 12:32:13.808 [main] ERROR TestFailureLogger -   - Failed tests count: 0
2025-09-20 12:32:13.808 [main] ERROR TestFailureLogger -   - Passed tests count: 1
2025-09-20 12:32:13.808 [main] ERROR TestFailureLogger -   - Skipped tests count: 0
2025-09-20 12:32:14.230 [main] ERROR TestFailureLogger - Failure report generated: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-reports\testcases.TC02_HomePage_validateCreateAdmin_P_2025-09-20_12-32-13_failure_report.html
2025-09-20 12:35:55.515 [main] ERROR TestFailureLogger - ❌ TEST FAILED: testcases.TC02_HomePage.validateCreateAdmin_P (Duration: 4846 ms)
2025-09-20 12:35:55.516 [main] ERROR TestFailureLogger - Failure reason: expected [true] but found [false]
2025-09-20 12:35:55.516 [main] ERROR TestFailureLogger - Stack trace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.failNotEquals(Assert.java:1578) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.assertTrue(Assert.java:57) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.assertTrue(Assert.java:67) ~[testng-7.8.0.jar:7.8.0]
	at testcases.TC02_HomePage.validateCreateAdmin_P(TC02_HomePage.java:46) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.8.0.jar:7.8.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:848) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestRunner.run(TestRunner.java:621) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:336) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1275) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuites(TestNG.java:1114) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.run(TestNG.java:1082) [testng-7.8.0.jar:7.8.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105) [testng-rt.jar:?]
2025-09-20 12:35:55.527 [main] ERROR TestFailureLogger - Test context information:
2025-09-20 12:35:55.528 [main] ERROR TestFailureLogger -   - Test name: Create PIM and Admin !
2025-09-20 12:35:55.528 [main] ERROR TestFailureLogger -   - Output directory: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-output\Running positive scenarios on main list of home page
2025-09-20 12:35:55.530 [main] ERROR TestFailureLogger -   - Start date: 2025-09-20T12:35:25.031+0300
2025-09-20 12:35:55.530 [main] ERROR TestFailureLogger -   - End date: null
2025-09-20 12:35:55.530 [main] ERROR TestFailureLogger -   - Failed tests count: 0
2025-09-20 12:35:55.531 [main] ERROR TestFailureLogger -   - Passed tests count: 1
2025-09-20 12:35:55.531 [main] ERROR TestFailureLogger -   - Skipped tests count: 0
2025-09-20 12:35:55.558 [main] ERROR TestFailureLogger - Failure report generated: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-reports\testcases.TC02_HomePage_validateCreateAdmin_P_2025-09-20_12-35-55_failure_report.html
2025-09-20 12:38:07.724 [main] ERROR TestFailureLogger - ❌ TEST FAILED: testcases.TC02_HomePage.validateCreateAdmin_P (Duration: 4877 ms)
2025-09-20 12:38:07.724 [main] ERROR TestFailureLogger - Failure reason: expected [true] but found [false]
2025-09-20 12:38:07.724 [main] ERROR TestFailureLogger - Stack trace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.failNotEquals(Assert.java:1578) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.assertTrue(Assert.java:57) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.Assert.assertTrue(Assert.java:67) ~[testng-7.8.0.jar:7.8.0]
	at testcases.TC02_HomePage.validateCreateAdmin_P(TC02_HomePage.java:46) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.8.0.jar:7.8.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:848) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestRunner.run(TestRunner.java:621) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:336) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1275) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuites(TestNG.java:1114) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.run(TestNG.java:1082) [testng-7.8.0.jar:7.8.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105) [testng-rt.jar:?]
2025-09-20 12:38:07.733 [main] ERROR TestFailureLogger - Test context information:
2025-09-20 12:38:07.733 [main] ERROR TestFailureLogger -   - Test name: Create PIM and Admin !
2025-09-20 12:38:07.734 [main] ERROR TestFailureLogger -   - Output directory: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-output\Running positive scenarios on main list of home page
2025-09-20 12:38:07.737 [main] ERROR TestFailureLogger -   - Start date: 2025-09-20T12:37:37.696+0300
2025-09-20 12:38:07.737 [main] ERROR TestFailureLogger -   - End date: null
2025-09-20 12:38:07.738 [main] ERROR TestFailureLogger -   - Failed tests count: 0
2025-09-20 12:38:07.738 [main] ERROR TestFailureLogger -   - Passed tests count: 1
2025-09-20 12:38:07.738 [main] ERROR TestFailureLogger -   - Skipped tests count: 0
2025-09-20 12:38:07.754 [main] ERROR TestFailureLogger - Failure report generated: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-reports\testcases.TC02_HomePage_validateCreateAdmin_P_2025-09-20_12-38-07_failure_report.html
2025-09-20 12:56:46.592 [main] ERROR TestFailureLogger - ❌ TEST FAILED: testcases.TC02_HomePage.validateCreateNewPIM_P (Duration: 28611 ms)
2025-09-20 12:56:46.680 [main] ERROR TestFailureLogger - Failure reason: Condition failed after 5 attempts.
2025-09-20 12:56:46.680 [main] ERROR TestFailureLogger - Stack trace:
java.lang.RuntimeException: Condition failed after 5 attempts.
	at pages.PageBase.longWait(PageBase.java:128) ~[classes/:?]
	at pages.P02_HomePage.confirmPIMsavedSuccessfully(P02_HomePage.java:133) ~[classes/:?]
	at testcases.TC02_HomePage.validateCreateNewPIM_P(TC02_HomePage.java:37) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.8.0.jar:7.8.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:848) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestRunner.run(TestRunner.java:621) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:336) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1275) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuites(TestNG.java:1114) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.run(TestNG.java:1082) [testng-7.8.0.jar:7.8.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105) [testng-rt.jar:?]
2025-09-20 12:56:46.747 [main] ERROR TestFailureLogger - Test context information:
2025-09-20 12:56:46.748 [main] ERROR TestFailureLogger -   - Test name: Create PIM and Admin !
2025-09-20 12:56:46.748 [main] ERROR TestFailureLogger -   - Output directory: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-output\Running positive scenarios on main list of home page
2025-09-20 12:56:46.843 [main] ERROR TestFailureLogger -   - Start date: 2025-09-20T12:56:08.366+0300
2025-09-20 12:56:46.844 [main] ERROR TestFailureLogger -   - End date: null
2025-09-20 12:56:46.845 [main] ERROR TestFailureLogger -   - Failed tests count: 0
2025-09-20 12:56:46.846 [main] ERROR TestFailureLogger -   - Passed tests count: 0
2025-09-20 12:56:46.848 [main] ERROR TestFailureLogger -   - Skipped tests count: 0
2025-09-20 12:56:47.032 [main] ERROR TestFailureLogger - Failure report generated: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-reports\testcases.TC02_HomePage_validateCreateNewPIM_P_2025-09-20_12-56-46_failure_report.html
2025-09-20 12:56:47.693 [main] ERROR TestFailureLogger - ❌ TEST FAILED: testcases.TC02_HomePage.validateCreateAdmin_P (Duration: 648 ms)
2025-09-20 12:56:47.693 [main] ERROR TestFailureLogger - Failure reason: Condition failed after 5 attempts.
2025-09-20 12:56:47.693 [main] ERROR TestFailureLogger - Stack trace:
java.lang.RuntimeException: Condition failed after 5 attempts.
	at pages.PageBase.longWait(PageBase.java:128) ~[classes/:?]
	at pages.P02_HomePage.createAdminPIM(P02_HomePage.java:150) ~[classes/:?]
	at testcases.TC02_HomePage.validateCreateAdmin_P(TC02_HomePage.java:44) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.8.0.jar:7.8.0]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.8.0.jar:7.8.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:848) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestRunner.run(TestRunner.java:621) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:336) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.8.0.jar:7.8.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1275) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.runSuites(TestNG.java:1114) [testng-7.8.0.jar:7.8.0]
	at org.testng.TestNG.run(TestNG.java:1082) [testng-7.8.0.jar:7.8.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105) [testng-rt.jar:?]
2025-09-20 12:56:47.695 [main] ERROR TestFailureLogger - Test context information:
2025-09-20 12:56:47.695 [main] ERROR TestFailureLogger -   - Test name: Create PIM and Admin !
2025-09-20 12:56:47.695 [main] ERROR TestFailureLogger -   - Output directory: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-output\Running positive scenarios on main list of home page
2025-09-20 12:56:47.696 [main] ERROR TestFailureLogger -   - Start date: 2025-09-20T12:56:08.366+0300
2025-09-20 12:56:47.696 [main] ERROR TestFailureLogger -   - End date: null
2025-09-20 12:56:47.696 [main] ERROR TestFailureLogger -   - Failed tests count: 1
2025-09-20 12:56:47.696 [main] ERROR TestFailureLogger -   - Passed tests count: 0
2025-09-20 12:56:47.696 [main] ERROR TestFailureLogger -   - Skipped tests count: 0
2025-09-20 12:56:47.698 [main] ERROR TestFailureLogger - Failure report generated: C:\Shady Automation Course\Projects During Live Sessions\Sesion_3\OrangeHRM\test-reports\testcases.TC02_HomePage_validateCreateAdmin_P_2025-09-20_12-56-47_failure_report.html
2025-09-20 12:56:47.718 [main] ERROR TestFailureLogger - Configuration method failed: TearDown - Error communicating with the remote browser. It may have died.
Build info: version: '4.24.0', revision: '748ffc9bc3'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [cb218ac03341b7500dcede8e70a80c4e, executeScript [script, args]]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 140.0.7339.128, chrome: {chromedriverVersion: 140.0.7339.185 (eeea00e459e..., userDataDir: C:\Users\hanya\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:61956}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:61956/devtoo..., se:cdpVersion: 140.0.7339.128, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: cb218ac03341b7500dcede8e70a80c4e
